// <auto-generated />
using FoostonWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System;

namespace FoostonWeb.Migrations
{
    [DbContext(typeof(FoostonDbContext))]
    [Migration("20180121205105_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("FoostonWeb.Models.EmailRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("EmailRegistrations");
                });

            modelBuilder.Entity("FoostonWeb.Models.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Change");

                    b.Property<string>("GamesBack");

                    b.Property<string>("Losses");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Percent");

                    b.Property<string>("PlusMinus");

                    b.Property<string>("PreviousPoints");

                    b.Property<string>("PreviousRank");

                    b.Property<int>("Rank");

                    b.Property<string>("Rating")
                        .IsRequired();

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("WeeksOff");

                    b.Property<string>("Wins");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Standings");
                });
#pragma warning restore 612, 618
        }
    }
}
